export type TextColor = "white" | "black";

export type Project = {
  title: string;
  slug: string;
  category: string[];
  img: string;
  /** Colour of the title/tags overlaid on the cover image. Pick based on the image background. */
  textColor: TextColor;
  /**
   * The cover is a UI screenshot. Cards and the project header show the whole
   * image (never cropped, even when zoomed on hover) over a blurred copy of
   * itself, with light text on top.
   */
  screenshot?: boolean;
  logo?: string;
  gallery?: string[];
  /** Screen recording shown inside a MacBook mockup on the project page */
  video?: { src: string; poster?: string };
  owner: string;
  date: string;
  services: string;
  duration: string;
  budget?: string;
  live: string;
  overview: string;
  objective: string;
  process: string;
  impact: string;
};

export const projects: Project[] = [
  {
    // For Post
    title: "ELXR Creative",
    slug: "elxr",
    category: ["Next.js", "Three.js", "GSAP", "3D Web"],
    img: "/images/elxr/hero-city.jpg",
    textColor: "white",
    video: {
      src: "/videos/elxr-demo.mp4",
      poster: "/images/elxr/poster.jpg",
    },

    // Sticky
    owner: "ELXR Creative",
    date: "September 2026",
    services: "Web Design, 3D Development, Frontend Engineering",
    duration: "1 Month",
    budget: "Client Project",
    live: "https://www.elxrnetwork.com",

    // Scroll
    overview:
      "ELXR Creative is a New York and New Jersey marketing agency built around one idea: attention is engineered, not bought. The site is a single-page experience that treats the agency as a distillery. A bottle fills with purple liquid while the page loads, a blueprint of Manhattan resolves into a fully rendered 3D city at night, and each of the six services is a bottle you can open in an interactive collection. Every number on the page carries the mechanism behind it, and no client is ever named.",

    objective:
      "The brief asked for a site that felt like a product launch rather than an agency brochure, while staying fast enough to load on a phone. The 3D city had to be real geometry with landmarks you could fly to, not a video backdrop, and the bottle collection needed to work as the primary navigation for services. Reduced motion, failed WebGL, and slow connections all had to degrade to something that still read as the same brand.",

    process:
      "The site is built on Next.js 14 with the App Router, Tailwind for layout, react-three-fiber for the city and bottle scenes, and GSAP ScrollTrigger for the scroll choreography. Copy lives in a single typed content file so the client can edit it without touching components. Manhattan is drawn first as a lightweight 2D map while the WebGL chunk downloads, then the rendered city fades in at the same orientation. The city itself is seven locally served glTF assets generated by a script, with a shared facade atlas for glazing and weathering, animated taxis and pedestrians, billboards that respond to selection, and drifting volumetric clouds. The bottles are three original glTF models with runtime glass and metal shaders and a liquid that glows in HDR. Intro freezes were solved by precompiling the ambient occlusion pass and warming reveal groups through the real render pipeline before the loader finishes.",

    impact:
      "The result is a marketing site that behaves like the work the agency sells. The load screen, the pour into the city, and the bottle carousel give the elixir metaphor a physical form instead of leaning on copy, and the whole journey runs at frame rate on a laptop and gracefully simplifies on mobile. Because content, tokens, and geometry are separated, the client can change headlines, colours, or services without a rebuild of the 3D scenes.",
  },
  {
    // For Post
    title: "Life OS",
    slug: "life-os",
    category: ["Swift", "iOS Development", "Supabase", "Plaid"],
    img: "/images/lifeos/v01-front.jpg",
    textColor: "white",
    logo: "/images/lifeos/logo.png",
    gallery: [
      "/images/lifeos/v02-front.jpg",
      "/images/lifeos/profile.jpg",
      "/images/lifeos/profile-2.jpg",
      "/images/lifeos/profile-3.jpg",
      "/images/lifeos/v03-perspective.jpg",
      "/images/lifeos/v04-notes.jpg",
      "/images/lifeos/v05-pinch.jpg",
      "/images/lifeos/v06-pinch.jpg",
      "/images/lifeos/v07-thumb.jpg",
      "/images/lifeos/v08-check.jpg",
      "/images/lifeos/v04-perspective.jpg",
    ],

    // Sticky
    owner: "Shiv Vyas",
    date: "Ongoing",
    services: "iOS Development, Swift, Supabase, Product Design",
    duration: "Ongoing",
    budget: "Personal Project",
    live: "https://github.com/shivvyas2/LifeOS",

    // Scroll
    overview:
    "Life OS is a native iOS app that brings the scattered parts of daily life into one operating system. Instead of switching between a calendar, a budgeting app, a fitness tracker, and a notes app, Life OS gives each of those a module inside a single home: Today, Plan, Money, Health, Body, Activity, Recovery, Social, Notes, and a Coach and Assistant layer that reads across all of them. The app is built in SwiftUI for iOS 26 with a shared LifeOSKit package, and is currently shipping to testers through TestFlight.",

  objective:
    "The goal was to design a personal system rather than another single-purpose app. Each module had to be useful on its own while feeding a shared picture of the day, so that the Coach and Assistant surfaces could reason about money, health, and plans together. Onboarding needed to stay short enough that a person could connect a bank account, sync health data, and see a meaningful Today screen within the first session.",

  process:
    "The project started with an engineering handbook that fixed the architecture, naming, and release process before the first screen was built, and that handbook now ships alongside the code. Features were built as isolated modules on top of LifeOSKit, with Supabase handling auth and sync. Connecting real bank accounts required Plaid Link, and because large US banks use OAuth, a small companion site on almanac.shivvyas.com was added to serve the Apple App Site Association file so the OAuth redirect lands back inside the app as a universal link. Release work followed a documented TestFlight checklist so builds could be cut repeatedly without surprises.",

  impact:
    "Life OS turns a dozen daily check-ins into one. Money, health, and plans live side by side, which makes patterns visible that separate apps hide, and the Coach layer can act on them. The module structure means new areas of life can be added without touching the rest of the app, and the documented handbook and release process make the project easy to return to and extend. It is the most complete expression so far of the idea that personal software should behave like an operating system, not a collection of tabs."
  },
  {
    // For Post
    title: "Astra",
    slug: "astra",
    category: ["Next.js", "iOS Development", "Claude AI", "Supabase"],
    img: "/images/Astra.png",
    textColor: "white",

    // Sticky
    owner: "Shiv Vyas",
    date: "August 26, 2026",
    services: "Full-Stack Development, iOS Development, AI Integration, Branding",
    duration: "5 Weeks",
    budget: "Personal Project",
    live: "https://astra.shivvyas.com",

    // Scroll
    overview:
    "Astra is an astrology product with a simple promise: computed, never guessed. Where most astrology apps serve generic sun-sign copy, Astra calculates a person's real birth chart from their birth date, time, and place, then uses Claude to write a reading grounded in those exact positions. It ships as a Next.js web app at astra.shivvyas.com and as a native iOS app that signs in with Apple and shares the same Supabase backend.",

  objective:
    "The objective was to make a reading feel personal and defensible at the same time. That meant doing the astronomy properly, handling time zones and historical locations correctly, and giving the language model only verified chart data to work from so the prose never invents a placement. Signup had to be as fast as possible on iOS, ideally two taps and a birthday, and the brand needed to feel cosmic without tipping into cliché.",

  process:
    "Chart calculation runs on Swiss Ephemeris compiled to WebAssembly, with time zone lookup resolving the birth location to the correct historical offset. Claude receives the computed chart as structured input and returns the interpretation, which is rendered as Markdown and can be exported to PDF. Supabase handles auth and storage, with email OTP on the web and native Sign in with Apple on iOS using a per-attempt nonce so tokens cannot be replayed. Push alerts, model cost tracking, and deployment are documented in the repo so the app can be operated, not just demoed. The landing page uses a full-bleed planetary hero and restrained typography to set the tone before a person ever enters their details.",

  impact:
    "Astra shows what an AI product looks like when the model is the writer rather than the source of truth. Every reading is traceable to a real chart, which gives people a reason to trust it and gives the product a defensible edge over template-based competitors. The shared backend between web and iOS meant the native app could launch without rebuilding any of the core logic, and the documented setup makes it straightforward to add new surfaces like a Mac or watch app later."
  },
  {
    // For Post
    title: "SATistics",
    slug: "satistics",
    category: ["Next.js", "Three.js", "FastAPI", "Claude AI"],
    img: "/images/SATistics.png",
    textColor: "black",
    screenshot: true,

    // Sticky
    owner: "Shiv Vyas",
    date: "November 20, 2025",
    services: "Game Development, Full-Stack Development, AI Integration",
    duration: "2 Days",
    budget: "Hackathon Project",
    live: "https://www.satistic.tech",

    // Scroll
    overview:
    "SATistics makes SAT and GRE practice something students actually want to open. It started at NYU Hacks as a set of arcade games with real SAT questions inside, and has grown into a full prep platform: six games including a first-person zombie shooter, an endless runner, Squid Game and Pac-Man, concept lessons for every exam topic with recommended video lessons, student profiles with goals and test-day countdowns, and a dashboard that points each student at their weakest topic. Answer correctly to keep playing; behind the games, an AI agent adapts the questions to each student.",

  objective:
    "The goal was to hold attention long enough for practice to work. The games had to be genuinely fun, not quizzes with a skin, and the questions had to match the real exams' formats rather than feel random. The redesign added the other half of studying: a way to learn a concept before drilling it, and a dashboard that turns scores into a clear next step, all in a visual identity that feels like a game studio rather than a test-prep company.",

  process:
    "The frontend is Next.js 14 with TypeScript and Tailwind, with Three.js powering the 3D games and a neo-brutalist design system mixing thick outlines and hard shadows with frosted-glass panels. Every game cover is custom SVG art. A FastAPI backend on Supabase handles auth, profiles, score tracking, and the learning agent, which reviews a student's history, finds weak topics, and uses Claude Haiku to write personalized questions checked against practice material found on the web. Lesson videos are found per topic through the YouTube Data API and ranked toward lesson-length videos from established prep channels. Both apps deploy on Vercel at satistic.tech.",

  impact:
    "SATistics shows that adaptive learning and play are not in tension. Students learn a concept, watch a lesson, and lock it in with a game loop they want to repeat, while the agent quietly steers practice toward what each person needs most. What began as a weekend hackathon build is now a complete SAT and GRE prep product, showing how far modern web tooling and an LLM can take a focused idea."
  },
  {
    // For Post
    title: "WhyKnot",
    slug: "whyknot",
    category: ["Next.js", "Supabase", "Data Visualization", "Fintech API"],
    img: "/images/WhyKnot.png",
    textColor: "black",
    screenshot: true,

    // Sticky
    owner: "Shiv Vyas",
    date: "August 7, 2026",
    services: "Full-Stack Development, Data Visualization, API Integration",
    duration: "Hackathon Build",
    budget: "Hackathon Project",
    live: "https://whyknot.vercel.app",

    // Scroll
    overview:
    "Restaurants choose new locations on instinct and a rented demographics report. The data that would actually answer where people are already ordering food sits inside consumers' own delivery accounts. WhyKnot is a two-sided platform built on Knot's Transaction Link that turns that data into a map. Diners connect DoorDash and Uber Eats in exchange for rewards, and restaurant owners see aggregate demand by neighborhood instead of guessing.",

  objective:
    "The goal was to prove that consented transaction data could replace scraped or purchased datasets for location decisions. That required two experiences that each had to stand on their own: a consumer portal where connecting an account felt safe and rewarding, and a business dashboard where demand showed up as a heatmap with scouting and per-area analytics rather than a spreadsheet. Everything that touched Knot had to be real, not mocked, so the demo would hold up to scrutiny.",

  process:
    "The app was built on Next.js 14 with the App Router, TypeScript, Supabase for Postgres and auth, Tailwind, and Leaflet for the map. All Knot integration lives in one module: a client-side Link flow, a server-side API client, session creation, per-merchant transaction sync, and webhook handlers for transaction and connection events. Two details cost real debugging time and are documented for the next person: Knot pins sync cursors to a stable external user id, and the merchant filter is development-only. A separate restaurant-stats backend powers the demand heatmap, and the hosted demo runs in a no-login demo mode so anyone can explore it.",

  impact:
    "WhyKnot reframes location intelligence as an exchange rather than a purchase: the diner gets rewards and better deals, the operator gets ground truth, and no one's data is bought or scraped. The working demo, along with a recorded walkthrough submitted for the hackathon, showed both sides of the marketplace functioning against a live financial data API. The clean separation of the Knot layer means the same foundation can extend to more merchants and more categories of local business."
  },
  {
    // For Post
    title: "Contextual Intelligence",
    slug: "contextual-intelligence",
    category: ["AI Agents", "Python", "LangGraph", "iOS Development"],
    img: "/images/Luna.png",
    textColor: "black",
    screenshot: true,

    // Sticky
    owner: "Shiv Vyas",
    date: "July 22, 2026",
    services: "AI Agent Development, Backend Engineering, iOS Development, Web Design",
    duration: "8 Months",
    budget: "Startup Project",
    live: "https://www.contextualintelligence.co",

    // Scroll
    overview:
    "Contextual Intelligence is an AI agent that lives in iMessage. Its public face is Clo, your Chief Life Officer. A person tells it what they love, who they want to see, and when they are free, and it quietly turns that into real plans: a dinner reservation, tickets, an introduction to someone worth meeting, a ride. Partner venues in New York receive the people they most want to reach. Behind the conversation is a FastAPI and LangGraph service on Google Gemini, with a marketing site, a Clerk-authenticated API, and a customized SwiftUI chat interface.",

  objective:
    "The aim was an assistant that acts rather than answers. The agent had to hold long-lived context about a person, decide when to reach out proactively, and complete tasks end to end through real integrations, all inside a messaging channel with no app to install. Consent had to be explicit at every step, especially for introductions between people, and the system had to gate access during launch, meter usage, and run safely with a staging instance beside production.",

  process:
    "Inbound iMessage webhooks are routed through deterministic handlers for access gating, consent flows, and RSVPs before falling through to a LangGraph agent with tools for reservations, events, people matching, personal apps, orders, and rides. Redis holds cache, coordination, and conversation checkpoints; Firestore stores users, RSVPs, and match embeddings. A Composio sidecar gives each person Google Calendar and Gmail access on their own terms. Background workers handle morning briefings, proactive plan suggestions, approval notifications, and profile embeddings. Resy credentials are stored in an encrypted vault for booking. The stack deploys as two systemd instances on one box, with an evals suite and test suite guarding agent behavior.",

  impact:
    "Contextual Intelligence demonstrates a full agent product rather than a chat demo: gated beta access, billing, proactive outreach with consent, and real bookings at real venues. Meeting people inside the messaging app they already use removes the biggest adoption barrier for a personal AI. For partner venues it is a direct channel to the customers who fit them best. The modular agent design, with capabilities unlocked progressively per person, provides a template for how consumer agents can grow in scope without overwhelming the people using them."
  },
  {
    // For Post
    title: "Trashee",
    slug: "trashee",
    category: ["React Native", "Next.js", "IoT", "Supabase"],
    img: "/images/Trashee.png",
    textColor: "white",
    screenshot: true,

    // Sticky
    owner: "Shiv Vyas",
    date: "July 15, 2026",
    services: "Mobile Development, Admin Dashboard, Web Design, Product Strategy",
    duration: "Ongoing",
    budget: "Startup Project",
    live: "https://trashee-website.shivvyas.com",

    // Scroll
    overview:
    "Trashee is a waste management platform for India built around a simple loop: trash it, earn it. Smart bins placed where people already are detect a deposit with onboard sensors, points land in the person's app before they walk away, and those points unlock coupons at nearby stores. Three apps serve the ecosystem, one each for citizens, partner businesses, and collectors, with an admin dashboard tying together users, partners, coupons, payouts, and statements.",

  objective:
    "The objective was to make recycling rewarding enough to become a habit, without the friction that kills most sustainability apps: no sorting quizzes, no photo uploads, no manual claims. Each stakeholder needed a purpose-built experience, and the business side had to be operable from day one, including partner onboarding, coupon management, payout approvals, and exportable financial statements, so the platform could launch commercially rather than as a pilot.",

  process:
    "The mobile apps are built in React Native with Expo and file-based routing, with Clerk handling authentication, QR and barcode scanning for deposits, a wallet for points and rewards, and a waste category guide. The admin dashboard is a Next.js App Router application on Supabase with role-gated access, KPI charts in Recharts, and CSV export for ledgers and partner payments. The marketing site uses Next.js, Framer Motion, and Three.js to present live impact numbers and explain the bin-to-reward flow. Work was organized in sprints from auth and navigation through scanning, rewards, and partner tooling, with RazorpayX and subscription billing planned for the India launch.",

  impact:
    "Trashee turns a civic chore into a rewards program and gives local businesses a new way to reach customers who share their values. Verified deposits from IoT bins remove fraud and paperwork from the reward loop, and the carbon rating in the app lets people see their own impact grow. The complete operator tooling means the company can onboard partners, approve payouts, and reconcile statements without engineering help, which is what turns a good idea into a business."
  },
  {
    // For Post
    title: "Inhale",
    slug: "inhale",
    category: [ "React Development","iOS Development", "Android Development","Clerk"],
    img: "/images/Inhale.png",
    textColor: "black",
    screenshot: true,

    // Sticky
    owner: "Shiv Vyas",
    date: "February 12, 2025",
    services: "React Development, iOS Development, Android Development, Clerk",
    duration: "2 Days",
   
    live: "https://github.com/shivvyas2/Inhale-Breathing-App",

    // Scroll
    overview:
    "Inhale is a comprehensive breathing and meditation application that builds upon the foundation of Calm Pulse. The platform offers guided sessions with customizable breathing techniques tailored to specific user needs such as focus, relaxation, and sleep improvement. Featuring techniques like Box Breathing and 4-7-8, Inhale enhances the meditation experience with haptic feedback synchronized to breathing patterns, allowing users to practice with their eyes closed. The app incorporates engagement features like daily streaks and point rewards for completed sessions, while also supporting local artists by integrating their focus tracks into the meditation experience.",

  objective:
    "Our primary objective was to create an accessible, feature-rich breathing and meditation platform that could serve users across various needs and preferences. The solution needed to provide personalized experiences while maintaining ease of use, with techniques specifically designed for different mental states. Each feature was crafted to enhance user engagement, promote consistent practice, and deliver tangible benefits for mental wellbeing through guided breathing exercises.",

  process:
    "Development began by expanding on the foundation of the Calm Pulse app, enhancing its core functionality with additional features. We focused on implementing customizable breathing techniques tailored to specific wellness goals, creating an intuitive interface for session guidance. The team incorporated haptic feedback technology to allow for eyes-closed practice, significantly enhancing the immersion of the breathing experience. We integrated mood tracking capabilities and personalized recommendations based on user history, along with motivation-enhancing features like daily streaks and completion points. Throughout the HackNYU event, team members Vighanesh Gaund and Adam Soliman contributed significantly to evolving the application, refining the user experience based on feedback and testing. The collaboration resulted in a functional prototype demonstrating the app's core capabilities.",

  impact:
    "Inhale addresses the growing need for accessible mental wellness tools by providing guided breathing techniques that can be practiced anywhere, anytime. The application empowers users to incorporate effective stress-management practices into their daily routines, potentially improving focus, relaxation, and sleep quality. By including features that encourage consistent practice through streaks and rewards, Inhale helps users develop sustainable wellness habits. The incorporation of local artists' focus tracks creates connections within the community while supporting creators. The haptic feedback innovation allows for truly immersive practice sessions, differentiating Inhale in the wellness app marketplace and making mindfulness more accessible to users seeking stress relief in their busy lives."
  },
  {
    // For Post
    title: "AuraMax",
    slug: "aura-max",
    category: [ "React Development","iOS Development", "Android Development","Clerk"],
    img: "/images/AuraMaxS3.png",
    textColor: "black",

    // Sticky
    owner: "Shiv Vyas",
    date: "March 29, 2025",
    services: "React Development, iOS Development, Android Development, Clerk",
    duration: "2 Days",
   
    live: "https://github.com/shivvyas2/PrincetonHacks",

    // Scroll
    overview:
    "Aura Max is an innovative micro-investment platform connecting small businesses with community investors. The platform creates a marketplace where local businesses can secure modest capital injections needed to sustain operations through challenging periods, while offering investors fractional profit sharing and unique perks. By democratizing investment in local enterprises, Aura Max addresses the critical funding gap that often leads to premature business closures, particularly for establishments that need smaller investments compared to venture-backed tech startups.",

  objective:
    "Our primary objective was to build a user-friendly platform that enables small business owners to present their funding needs while allowing community members to make micro-investments with minimal risk. The solution needed to be accessible to both business owners with limited financial expertise and everyday investors looking to support local establishments while receiving tangible benefits. Each feature was designed to foster trust, transparency, and mutual benefit between businesses and their community investors.",

  process:
    "Development began with identifying the funding challenges unique to small local businesses. We focused on creating essential features including business profiles, investment options with clear terms, and a secure transaction system. The platform was designed with a simple, inviting interface that makes investment opportunities easy to discover and understand. We incorporated dual-value incentives, combining financial returns with experiential perks like exclusive discounts or special access. Throughout the 48-hour hackathon, we continuously refined the concept based on mentor feedback, particularly focusing on the practical implementation of community-based investment models and regulatory considerations. The rapid development process resulted in a working prototype that demonstrates the platform's core functionality.",

  impact:
    "Aura Max bridges the critical gap between small businesses needing modest capital and community members seeking meaningful local investment opportunities. The platform empowers businesses to maintain operations during challenging periods while pivoting toward sustainability. For investors, it offers a way to diversify investments with manageable risk while directly supporting community establishments they value. By creating this symbiotic relationship, Aura Max strengthens local economic ecosystems and transforms community members into stakeholders in businesses they frequent. The successful prototype development during the hackathon demonstrated both the technical feasibility and market potential of this community-centered investment approach."
  },
  {
    // For Post
    title: "Ghor Kalyug",
    slug: "ghor-kalyug",
    category: ["Node.js", "React Development", "Backend Development", "Google Cloud Platform"],
    img: "/images/project2_1.jpeg",
    textColor: "white",
    screenshot: true,

    // Sticky
    owner: "Shiv Vyas",
    date: "Dec 12, 2024",
    services: "Backend Development, Frontend Development, Google Cloud Platform",
    duration: "20 Days",
    budget: "Class Project",
    live: "https://frontend-dot-gen-lang-client-0403310649.ue.r.appspot.com/home",

    //Scroll
    overview:
    "In today’s digital-first learning environment, students often need flexible, personalized study tools that go beyond traditional methods. Our quiz system was designed to empower students to learn any topic by uploading their own content and data. By selecting the topic, difficulty level, and number of questions, learners can generate quizzes tailored to their unique needs. This self-directed approach maximizes engagement and helps each student focus on the areas that matter most to them.",

  objective:
    "The primary goal was to create an intuitive quiz-building platform where students can effortlessly turn their study materials into interactive quizzes. Students needed the freedom to pick which subject or chapter they’d focus on, as well as fine-tune quiz difficulty and length. Another crucial objective was to enable immediate feedback through answer review, allowing students to learn from their mistakes and reinforce their knowledge. From the branding perspective, we wanted to establish a modern, student-friendly identity that emphasizes personalization, simplicity, and an encouraging learning atmosphere.",

  process:
    "We began by conducting user research with students across different grade levels and academic disciplines to identify pain points in existing quiz tools. Prototyping focused on a clean, uncluttered interface where uploading materials, selecting topics, and configuring quiz settings could be done with minimal steps. Multiple rounds of usability testing helped us refine the quiz-generation workflow, ensuring it remained straightforward yet flexible for advanced customization. We developed a cohesive brand identity—complete with a fresh color palette, friendly typography, and playful iconography—to communicate accessibility and motivation. Throughout the design phase, we iterated on the user experience for both the quiz creation and completion processes, emphasizing clear feedback and insightful result reviews that guide students toward deeper understanding.",

  impact:
    "The launch of the quiz system made it simpler for students to study on their own terms. By giving them control over which topics to focus on and how challenging the questions should be, it encourages personalized, self-paced learning. The integrated review feature offers immediate feedback, which has proven to boost retention and confidence. As a result, adoption has grown steadily, with students reporting higher engagement and improved test scores. From a branding standpoint, the system’s approachable design and positive tone have resonated, creating an active community of learners who appreciate the platform’s flexibility and effectiveness."
  },
  {
    // For Post
    title: "FuteurCredX",
    slug: "futeur-ai",
    category: ["React Development", "UIUX Design", "Branding", "Fintech"],
    img: "/images/FuteurCredX.png",
    textColor: "white",
    screenshot: true,

    // Sticky
    owner: "FuteurCredX (formerly Futeur AI)",
    date: "Jan 6, 2025",
    services: "React Development, UIUX design, Branding, Rebrand",
    duration: "Ongoing",

    live: "https://futeurcredx.com/",

    // Scroll
    overview:
    "FuteurCredX is the rebrand and full redesign of Futeur AI: a business-funding marketplace that helps US business owners decide what their capital needs to do before they compare offers. Instead of asking how much they can borrow, owners start from the business move (building capacity, bridging timing, buying an asset, unlocking invoices, or making a long move) and a live capital routing table maps it to the financing structure built for it, from term loans and lines of credit to SBA loans, equipment financing, revenue-based financing, and invoice factoring.",

  objective:
    "The objective was to turn a generic AI-for-SMEs product into a clear, trustworthy funding guide. Owners needed to understand how each structure works, what pressure it puts on cash flow, and how to exit it, before ever talking to a provider. The brand had to read as serious, calm financial advice rather than a lead-capture form, and the experience had to work for owners in English, Spanish, Mandarin, Vietnamese, Korean, Russian, Japanese, and Hebrew.",

  process:
    "The redesign replaced the old dashboard aesthetic with an editorial identity: a serif display face, a deep green and paper palette, monospace labels, and hard-edged panels that make financial structures feel inspectable. The centerpiece is the capital routing table, an interactive component that walks a chosen business move through job, profile, structure, and exit, and links into a decision desk for each product. A Funding Lab adds payment and readiness tools that work without a credit check, and a one-click pre-qualification flow lets owners explore paths in minutes. The site is fully localized across eight languages.",

  impact:
    "FuteurCredX gives small-business owners a deliberate way to compare unlike financing mechanisms, bringing cost, pressure, and exit into view before they sign. The rebrand repositions the company from an AI analytics tool to a funding marketplace with a distinct, credible voice, and the routing-first experience turns a confusing category into a set of clear choices an owner can actually reason about."
  },
  {
    // For Post
    title: "FuteurCred",
    slug: "futeur-cred",
    category: ["React-Native", "Swift", "Android"],
    img: "/images/project3_1.png",
    textColor: "black",
    screenshot: true,

    // Sticky
    owner: "Futeur AI",
    date: "Ongoing",
    services: "React-Native Development, UIUX Design, Swift, Android",
    duration: "6 Months",
    budget: "Internal Project",
    live: "https://www.futeur.ai/",

    //Scroll
    overview:
    "Futeur AI is a cutting-edge business intelligence solution specifically designed for small and medium-sized enterprises (SMEs). By harnessing real-time data analytics and advanced AI algorithms, Futeur AI empowers businesses to predict trends, optimize operations, and accelerate growth. This project aimed to create a seamless, forward-thinking platform that embodies innovation and accessibility, reflecting the brand’s commitment to democratizing AI for everyday business use.",

  objective:
    "Our primary objective was to design a user-friendly interface and brand identity that resonates with time-strapped entrepreneurs and business owners. The platform had to be intuitive enough for non-technical users while offering robust, data-driven insights for strategic decisions. From forecasting to survival feasibility analysis, Futeur AI’s features were developed to give SMEs an edge in a rapidly evolving marketplace. Every element needed to reinforce trust, forward-thinking innovation, and tangible value.",

  process:
    "The journey began with extensive market research and user interviews to understand the unique hurdles small businesses face. We then mapped out core features—real-time analytics dashboards, predictive modeling, and social-economic trend tracking—to help business owners make data-backed decisions quickly. During the design phase, wireframes and prototypes were iterated to ensure a frictionless user flow. A sleek, modern aesthetic was chosen to signal innovation and accessibility, using a blend of vibrant accent colors and cooler base tones, reflecting Futeur AI’s balance between approachability and cutting-edge technology. Branding elements, including a bold logo and contemporary typography, further emphasized the sense of dynamic progress and reliability. Throughout development, we consistently revisited user feedback to refine the platform’s overall experience, ensuring it remained as practical as it was futuristic.",

  impact:
    "Futeur AI’s final design speaks directly to a tech-savvy yet time-constrained audience, clearly communicating the brand’s dedication to real-time, predictive insights. The cohesive brand identity—across platform dashboards, website materials, and marketing assets—reinforces trust and authority in the AI-driven solutions space. By aligning the platform’s functionality with a forward-focused visual design, Futeur AI successfully positions itself as the go-to partner for small businesses seeking sustainable growth and operational resilience, ultimately bridging the gap between cutting-edge innovation and everyday business needs.",
  },
  {
    // For Post
    title: "CalmPulse",
    slug: "calmpulse",
    category: ["Android", "UIUX Design", "Firebase"],
    img: "/images/project4_1.png",
    textColor: "black",

    // Sticky
    owner: "Shiv Vyas",
    date: "07 December, 2024",
    services: "UIUX, Android Development, Firebase",
    duration: "30 Days",
    budget: "Class Project",
    live: "https://github.com/shivvyas2/Team-1-Calm-Pulse-",

    //Scroll
    overview:
    "Calm Pulse is an application crafted to promote wellness and well-being by offering guided breathing exercises—drawing inspiration from the Apple Watch’s renowned breathing app. Recognizing that effective stress relief can be achieved through simple, accessible techniques, Calm Pulse leverages structured breathing to help users reduce anxiety, enhance focus, and improve both mental and physical health. Even a few minutes of daily practice has been shown to significantly reduce stress, elevate mood, boost energy, and sharpen concentration.",

  objective:
    "The core objective of Calm Pulse is to encourage users to embrace the power of daily, intentional breathing. By employing gentle guidance, structured sessions, and progress tracking, the app aims to seamlessly integrate well-being practices into everyday life. We placed emphasis on designing an intuitive interface that balances simplicity with aesthetic appeal, ensuring users remain focused on their breathing exercises rather than navigating a complex interface. Additionally, branding and visual design were developed to evoke calmness and reassurance, appealing to those seeking easy-to-adopt wellness solutions.",

  process:
    "We began by researching various guided breathing techniques and studying how existing apps—like the Apple Watch breathing feature—engage and retain users. Armed with these insights, we developed wireframes and prototypes that centered on minimalistic visuals, gentle animations, and straightforward navigation. User testing guided each design iteration, ensuring the app remained approachable for beginners while still engaging more experienced users. We incorporated short but consistent practice prompts, session reminders, and a rewards system to encourage daily participation. Throughout the development cycle, our focus stayed on fine-tuning the user experience so that opening Calm Pulse feels instantly calming and seamless.",

  impact:
    "Calm Pulse has successfully lowered the barrier to entry for individuals seeking consistent, time-efficient stress management tools. Through its guided breathing sessions and tailored reminders, users have reported improvements in stress levels, mood, and overall focus with just a few minutes of practice each day. The clear, serene interface and inviting brand identity have cultivated a sense of trust and familiarity among users. By simplifying both the visual design and the breathing techniques, Calm Pulse not only increases adoption but also helps foster a lasting habit of mindful, daily wellness."

  },
  {
    // For Post
    title: "Finance Tracker",
    slug: "finance-tracker",
    category: ["Swift", "iOS Development", "Firebase"],
    img: "/images/project5_1.jpeg",
    textColor: "black",

    // Sticky
    owner: "Shiv Vyas",
    date: "02 July, 2024",
    services: "Swift, Illustration",
    duration: "9 Days",
    budget: "Hobby Project",
    live: "https://github.com/shivvyas2/ExpenseTracker--iOS",

    //Scroll
    overview:
    "This finance tracking app is designed to simplify personal money management for everyday users. By offering an intuitive interface and essential features—like expense categorization, budget creation, and simple analytics—the app empowers individuals to monitor their cash flow with minimal effort. The vision behind this project was to create a user-friendly solution that helps people build healthy financial habits, track their progress over time, and ultimately gain confidence in their financial future.",

  objective:
    "Our main objective was to develop a streamlined application that encourages consistent tracking of income and expenses. To achieve this, we focused on an uncomplicated layout, clear navigation, and real-time data insights. From setting monthly budgets to categorizing transactions, each interaction was designed to be quick, straightforward, and informative. Another key aspect of the project was to establish a visual identity that evokes trust, reliability, and accessibility—critical elements for a tool handling personal finances. The end result is a brand and user experience that makes money management feel approachable rather than intimidating.",

  process:
    "Developing the finance tracker involved thorough research into user behavior and pain points, including interviews with people who had varying levels of financial literacy. This allowed us to identify crucial features, such as real-time expense updates, reminders for recurring payments, and the ability to easily categorize or tag transactions. We started with low-fidelity wireframes, gradually incorporating user feedback to enhance clarity and usability.",

  impact:
    "Since its release, the app has proven helpful for individuals looking to better understand and control their finances. Early adopters report feeling more in control of their money through consistent tracking and automated reminders. The straightforward interface encourages regular use, contributing to improved budgeting habits and reduced financial stress. The brand’s approachable, friendly design resonates with users, positioning the finance tracker as an indispensable companion for anyone aiming to take charge of their personal finances. Its simple yet effective approach has paved the way for future enhancements that will continue to streamline the user’s journey to financial well-being.",
  },
];

